trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create"),
    path('confirm/', views.confirm, name="confirm"),
    path('daily_route/', views.daily_route, name="daily_route")


    
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    zip_code = models.CharField(max_length=50)
    weekly_pickup = models.CharField(max_length=50)
    onetime_pickup = models.DateField(max_length=50, null = True)
    nonsuspended = models.DateField(max_length=50, null = True)

    def __str__(self):
        return self.name 

trash_collector/employees/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.apps import apps
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from .models import Employee
from datetime import date

# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.

def index(request):
    # This line will get the Customer model from the other app, it can now be used to query the db for Customers
    Customer = apps.get_model('customers.Customer')
    all_customers = Customer.objects.all()
    user =request.user
    logged_in_employee = Employee.objects.get(user=user)
    try: 
        logged_in_employee = Employee.objects.get(user=user)       
        return HttpResponseRedirect(reverse('employees:daily_view')) 
    except:
        return HttpResponseRedirect(reverse('employees:create'))
    

def create(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get('name')
        zip_code = request.POST.get('zip_code')
        new_employee = Employee(name = name, user = user, zip_code = zip_code)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')


def confirm(request, user_id):
    Customers = apps.get_model('customers.Customer')
    customer_charge = Customers.objects.get(pk = user_id)
    context = { 'new_balance': customer_charge}
    if request.method == 'POST':
        if customer_charge.balance == None:
            customer_charge.balance = 0
        customer_charge.balance += 4
        customer_charge.save()
        return HttpResponseRedirect(reverse('employees:daily_view'))
    else:
        return render(request, 'employees/confirm.html', context)
    
def daily_route(request): 
    Customer = apps.get_model('customers.Customer')
    all_customers = Customer.objects.all()
    user =request.user
    logged_in_employee = Employee.objects.get(user=user)
    two_date = date.today()
    this_day = str(date.today())
    weekday = request.POST.get('day_of_the_week')
    todays_customers = []
    for customer in all_customers: 
        customer_suspend_start = str(customer.suspend_start)
        customer_suspend_end = str(customer.suspend_end)
        if  this_day < customer_suspend_start or this_day > customer_suspend_end:     
            if customer.zip_code == logged_in_employee.zip_code and (customer.weekly_pickup == weekday or customer.one_time_pickup == weekday) :
                todays_customers.append(customer)    
    return HttpResponseRedirect(reverse('employees:daily_view'))

    context = { 'todays_customers' : todays_customers,
                'weekday': weekday}
    return render(request,'employees/index.html', context)

trash_collector/employees/templates/employees/confirm.html
{% extends 'base.html' %}

{% block title %} New Employent Set-up {% endblock %}
{% block header %} New Employment Set-Up {% endblock %}

{% block content %}

<form action="{% url 'employees:confirm' charge_customer.id %}" method='POST'>
  {% csrf_token %}
  <h3> Confirm pickup for {{charge_customer.name}} at {{charge_customer.address}} </h3>
  Confirm: <input type = 'checkbox' name='balance' id ='balance'><br>
  <input type = 'submit' value = 'Add Charge'>
</form>
{% endblock %}

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %} New Employee Set-up {% endblock %}
{% block header %} New Employee Set-Up {% endblock %}

{% block content %}

<form action="{% url 'employees:create' %}" method = "POST">
  {% csrf_token %}

  <h2>Please fill out the following info: </h2><br>
  <table>
    <tr><td> Name:</td><td> <input type = "text" name = "name" id="name"></td></tr><br>
    <tr><td> Zip Code:</td><td> <input type = "text" name = "zip_code" id="zip_code"></td></tr><br>
    <input type = "submit" value="Create Account">
  </form>

  {% endblock %}

trash_collector/employees/templates/employees/daily_route.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Daily View {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <br><br>
    <h2> Here are the customers on your route today: </h2>
    <table>
      <tr><td> Name:</td><td>{{customer}}</td></tr><br>
      <tr><td> Street Address:</td><td>{{customer.street_address}}</td></tr><br>
      <tr><td> Zip Code:</td><td> {{customer.zip_code}}</td></tr><br>
      <tr><td> Weekly Pickup:</td><br>
      <tr><td> Account Balance: </td>
    </table>

    <table>
      {% for customer in all_customers %}
      {% if weekday == customer.weekly_pickup %}
      <form action = "{% url 'employees:daily_route' %}" name="add_payment" id="add_payment" method='POST'>
        {% csrf_token %}
      
      
      





     
    </table>
    {% endif %}  
    {% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %} Employee Home{% endblock %}
{% block header %} Employee Home {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!
  <h2>List of your routes today</h2>
    <table>
      {% for customer in todays_customers %}
      {% if weekday == customer.weekly_pickup_day%}
      <form action = "{% url 'employees:daily_route' %}" name="add_charge" id="add_charge" method='POST'>
        {% csrf_token %}

        {% for customer in all_customers %}         
        <table>
          <tr><td> Name:</td><td>{{customer}}</td></tr><br>
          <tr><td> Zip Code:</td><td> {{customer.zip_code}}</td></tr><br>
          <tr><td> Weekly Pickup:</td><td>{{customer.weekly_pickup}}</td></tr><br>
          <tr><td> Suspend Service Start: </td><td>{{customer.suspend_start}}</td></tr><br>
          <tr><td> Suspend Service End: </td><td>{{customer.suspend_end}}</td></tr><br>
          <tr><td> One-time Pickup: </td><td>{{customer.one_time_pickup}}</td></tr><br>
          <tr><td> Account Balance: </td><td>{{customer.balance}}</td></tr><br>

  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}

{% endblock %}