trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path
from django.contrib import admin
from django.views.generic import RedirectView

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('new/', views.create, name="create"),
    path('detail/', views.detail, name="detail"),
    path('change_pickup/', views.change_pickup, name="change_pickup"),
    path('suspend/', views.suspend, name="suspend"),
    path('pickup/', views.pickup, name="pickup"),
    # path('delete/', views.delete, name='delete'),
    path('', RedirectView.as_view(url = '/customers/'))
      
]
    

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/customers/models.py
from django.db import models
import django.utils.timezone 
# Create your models here.

# TODO: Finish customer model by adding necessary properties to fulfill user stories


class Customer(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    street_address = models.CharField(blank=True, max_length=50)
    zip_code = models.CharField(default=True, max_length=5)
    balance = models.IntegerField(null=True)
    weekly_pickup = models.CharField(null=True, max_length=50)
    one_time_pickup = models.DateField(null=True, blank=True)
    suspend_start = models.DateField(null=True, blank=True)
    suspend_end = models.DateField(null=True, blank=True)
 
    def __str__(self):
        return self.name

trash_collector/customers/views.py
# from trash_collector.customers.apps import CustomersConfig
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.apps import apps
from django.shortcuts import redirect, render
from .models import Customer
from django.urls import reverse


# Create your views here.

# TODO: Create a function for each path created in customers/urls.py. Each will need a template as well.


def index(request):
    # The following line will get the logged-in in user (if there is one) within any view function
    user = request.user         
    try: 
        logged_in_customer = Customer.objects.get(user=user)
        context = { 
        'logged_in_customer': logged_in_customer
        # This line inside the 'try' will return the customer record of the logged-in user if one exists
    }    
    except:
        # TODO: Redirect the user to a 'create' function to finish the registration process if no customer record found
        return HttpResponseRedirect(reverse('customers:create'))
    return render(request,'customers/index.html', context)

    # It will be necessary while creating a Customer/Employee to assign request.user as the user foreign key
def create(request):
    
    if request.method == 'POST':
        name = request.POST.get('name')
        user = request.user
        street_address = request.POST.get('street_address')
        zip_code = request.POST.get('zip_code')
        weekly_pickup = request.POST.get('weekly_pickup')
        one_time_pickup = request.POST.get('one_time_pickup')
        new_customer = Customer(name=name, user=user, zip_code=zip_code, weekly_pickup=weekly_pickup,street_address=street_address, one_time_pickup=one_time_pickup)
        new_customer.save()
        return HttpResponseRedirect(reverse('customers:index'))

    else:
      
        return render(request, 'customers/create.html')
   

def detail(request):
    user = request.user
    logged_in_customer = Customer.objects.get(user=user)
    context = { 
        'logged_in_customer': logged_in_customer
    }    
    return render(request, 'customers/detail.html', {'customer': logged_in_customer})

def change_pickup(request):
     user = request.user
     customer = Customer.objects.get(user=user)
     if request.method == 'POST':
        change_pickup = request.POST.get('change_pickup')
        customer.weekly_pickup = change_pickup
        customer.save()
        return HttpResponseRedirect(reverse('customers:detail'))

     else:
        context ={'customer':customer}
        return render(request, 'customers/change_pickup.html', context)

def suspend(request):
     user = request.user
     customer = Customer.objects.get(user=user)
     if request.method == 'POST':
         customer.suspend_start = request.POST.get('suspend_start')
         customer.suspend_end = request.POST.get('suspend_end')
         customer.save()
         return HttpResponseRedirect(reverse('customers:detail'))
     else:
        context ={'customer':customer}
        return render(request, 'customers/suspend.html',context)

def pickup(request):
     user = request.user
     customer = Customer.objects.get(user=user)
     if request.method == 'POST':
         customer.one_time_pickup = request.POST.get('one_time_pickup')
         customer.save()
         return HttpResponseRedirect(reverse('customers:detail'))
     else:
        context ={'customer':customer}
        return render(request, 'customers/pickup.html',context)

# def delete(request):
#     user = request.user
#     customer = Customer.objects.get(user=user)
#     customer.delete()
#     return HttpResponseRedirect(reverse('players:detail'))

    # , suspend_start, suspend_end, one_time_pickup

trash_collector/customers/templates/customers/change_pickup.html
{% extends 'base.html' %}

{% block title %} Change Pick-Up {% endblock %}

{% block header %} Change the Day of Your Weekly Pick-up {% endblock %}

{% block content %}
<p><a href="{% url 'home' %}">Home</a>

<form action="{% url 'customers:change_pickup' %}" method = "POST">
  {%csrf_token%}
  Your current weekly pickup is on {{customer.weekly_pickup}} of every month.<br>
  Enter your new weekly pickup day: <input type="text" value='{{customer.change_pickup}}' name="change_pickup" id="change_pickup"><br>
    <input type="submit" value="Update!">
</form>
{% endblock %}

trash_collector/customers/templates/customers/create.html
{% extends 'base.html' %}

{% block title %} Account Set-up {% endblock %}
{% block header %} New Account Set-Up {% endblock %}

{% block content %}
<p><a href="{% url 'home' %}">Home</a></p>  
<form action="{% url 'customers:create' %}" method = "POST">
  {% csrf_token %}
  <h2>Please fill out the following fields to create your account: </h2><br>
  <table>
      <tr><td> Name:</td><td> <input type = "text" name = "name" id="name"></td></tr><br>
      <tr><td> Street Address:</td><td> <input type = "text" name = "street_address" id="street_address"></td></tr><br>
      <tr><td> Zip Code:</td><td> <input type = "text" name = "zip_code" id="zip_code"></td></tr><br>
      <tr><td> Weekly Pickup:</td><td> <input type = "text" name = "weekly_pickup" id="weekly_pickup"></td></tr><br>
      <tr><td> Suspend Start:</td><td> <input type = "date" name = "suspend_start" id="suspend_start"></td></tr><br>
      <tr><td> Suspend End:</td><td> <input type = "date" name = "suspend_end" id="suspend_end"></td></tr><br>
  </table>
  <input type = "submit" value="Create Account">
</form>
  
{% endblock %}

trash_collector/customers/templates/customers/detail.html
{% extends 'base.html' %}

{% block title %} Customer Details {% endblock %}

{% block header %} Customer Account Details {% endblock %}

{% block content %}
  
<form action="{% url 'customers:index' %}" method = "POST">
  {% csrf_token %}
  <h2>Your account details are listed below.</h2>
  <a href="{% url 'customers:index' %}">Home</a><br>
  If you would like to change the day of your weekly pick-up, click here: <a href="{% url 'customers:change_pickup' %}">Change Weekly Pickup </a><br>
  If you would like to schedule a one-time pick up, select: <a href="{% url 'customers:pickup' %}">One-Time Pickup </a><br>
  
  Need to suspend your service? Click here: <a href="{% url 'customers:suspend' %}">Suspend Service</a><br>
  <table>
        <tr><td> Name:</td><td>{{customer}}</td></tr><br>
        <tr><td> Street Address:</td><td>{{customer.street_address}}</td></tr><br>
        <tr><td> Zip Code:</td><td> {{customer.zip_code}}</td></tr><br>
        <tr><td> Weekly Pickup:</td><td>{{customer.weekly_pickup}}</td></tr><br>
        <tr><td> Suspend Service Start: </td><td>{{customer.suspend_start}}</td></tr><br>
        <tr><td> Suspend Service End: </td><td>{{customer.suspend_end}}</td></tr><br>
        <tr><td> One-time Pickup: </td><td>{{customer.one_time_pickup}}</td></tr><br>
        <tr><td> Account Balance: </td><td>{{customer.balance}}</td></tr><br>
      </table>
      
{% endblock %}

trash_collector/customers/templates/customers/index.html
{% extends 'base.html' %}

{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Customer Home {% endblock %}
{% block header %} Customer Home {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello, {{ user.username }}! Welcome to your customer portal. Here, you are able to view your account, adjust your trash pick-up day, and suspend services.<br>
    <br>
    Get started by clicking the link to view your account details.<br>
    <a href="{% url 'customers:detail' %}">Customer Account Details</a>
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  
  
  {% endif %}
{% endblock %}

trash_collector/customers/templates/customers/pickup.html
{% extends 'base.html' %}

{% block title %} Schedule Pick-Up {% endblock %}

{% block header %} Schedule a One-Time Pick-Up Request {% endblock %}

{% block content %}
<p><a href="{% url 'home' %}">Home</a></p>

<form action="{% url 'customers:pickup' %}" method = "POST">
  {%csrf_token%}

  Enter the date for your one-time pickup: <input type="date" value='{{customer.one_time_pickup}}' name="one_time_pickup" id="one_time_pickup"><br>
    <input type="submit" value="Submit!">
</form>

{% endblock %}

trash_collector/customers/templates/customers/suspend.html
{% extends 'base.html' %}

{% block title %} Suspend Service {% endblock %}

{% block header %} Suspend Service Request {% endblock %}

{% block content %}
<p><a href="{% url 'home' %}">Home</a></p>

<form action="{% url 'customers:suspend' %}" method = "POST">
  {%csrf_token%}

  Suspend Start:  <input type="date" value='{{customer.suspend_start}}' name="suspend_start" id="suspend_start"><br>
  Suspend End:  <input type="date" value='{{customer.suspend_end}}' name="suspend_end" id="suspend_end"><br>
  <input type="submit" value="Submit!">
</form>

{% endblock %}